log_level: "info"
tracing:
  endpoint: "jaeger:4318"
  service_name: "currency-watcher-bot"
bot:
  token: "currency-watcher-bot-token"
postgres:
  connection: "host=postgres port=5432 user=bot password=bot dbname=bot sslmode=disable"
