output = "shared/models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
  dbname = "bot"
  host   = "postgres"
  port   = 5432
  user   = "bot"
  pass   = "bot"
  schema = "public"
  sslmode= "disable"
  blacklist = ["migrations"]