// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Currency      string
	Users         string
	UsersCurrency string
}{
	Currency:      "currency",
	Users:         "users",
	UsersCurrency: "users_currency",
}
