// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Currencies", testCurrencies)
}

func TestDelete(t *testing.T) {
	t.Run("Currencies", testCurrenciesDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Currencies", testCurrenciesQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Currencies", testCurrenciesSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Currencies", testCurrenciesExists)
}

func TestFind(t *testing.T) {
	t.Run("Currencies", testCurrenciesFind)
}

func TestBind(t *testing.T) {
	t.Run("Currencies", testCurrenciesBind)
}

func TestOne(t *testing.T) {
	t.Run("Currencies", testCurrenciesOne)
}

func TestAll(t *testing.T) {
	t.Run("Currencies", testCurrenciesAll)
}

func TestCount(t *testing.T) {
	t.Run("Currencies", testCurrenciesCount)
}

func TestHooks(t *testing.T) {
	t.Run("Currencies", testCurrenciesHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Currencies", testCurrenciesInsert)
	t.Run("Currencies", testCurrenciesInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("Currencies", testCurrenciesReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Currencies", testCurrenciesReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Currencies", testCurrenciesSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Currencies", testCurrenciesUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Currencies", testCurrenciesSliceUpdateAll)
}
